server:
    port: 8091

# H2
spring:
    h2:
        console:
            enabled: true
            path: /h2
# Datasource
    datasource:
        url: jdbc:h2:file:~/test
        username: sa
        password:
        driver-class-name: org.h2.Driver
        validationQuery:  SELECT 1

# ===============================
# = JPA / HIBERNATE
# ===============================
    jpa:
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            ddl-auto: create-drop
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

security:
    password.encryption.key: E1BB463D57KAE7ABDBBE8091F9CE83DF

ethereum:
    url: http://127.0.0.1:8501
